"""Golden-file end-to-end tests.
"""Golden-file end-to-end tests.

Every fixture tree goes through the real pipeline in ``--yes`` mode and is
byte-compared against ``golden/<fixture>.core``. Fixtures are discovered, not
listed, so a new fixture fails here until its golden exists. Regenerate with
``python tests/emit_fixtures.py tests/golden`` and review the diff.

Byte comparison is the contract, down to key order and indentation. The one
exception is the version in the generated-by comment, folded to a fixed token
on both sides so a version bump does not invalidate every golden. test_emit.py
pins that line's exact format instead.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from emit_fixtures import FIXTURES, emit_fixture

GOLDEN = Path(__file__).resolve().parent / "golden"

FIXTURE_NAMES = sorted(p.name for p in FIXTURES.iterdir() if p.is_dir())

_GENERATED_BY_VERSION = re.compile(rb"^(# Generated by autocore )v\S+", re.M)


def _normalized(data: bytes) -> bytes:
    """`data` with the generated-by version folded to a fixed token."""
    return _GENERATED_BY_VERSION.sub(rb"\1vVERSION", data)


def test_every_fixture_is_discovered() -> None:
    # An empty parametrize list would pass silently if fixtures/ ever moved.
    assert FIXTURE_NAMES


@pytest.mark.parametrize("name", FIXTURE_NAMES)
def test_fixture_output_matches_its_golden_up_to_the_version(name: str) -> None:
    golden = GOLDEN / f"{name}.core"
    assert golden.is_file(), (
        f"no golden for fixture '{name}': generate it with "
        "'python tests/emit_fixtures.py tests/golden' and review it"
    )

    text = emit_fixture(FIXTURES / name)

    assert _normalized(text.encode("utf-8")) == _normalized(golden.read_bytes())
