"""Golden-file end-to-end tests.

Every fixture directory runs through the real pipeline — Scan, Parse, Resolve,
Emit — in ``--yes`` semantics (defaults, no defines) and is byte-compared
against ``golden/<fixture>.core``. Fixtures are discovered, not listed, so
adding a fixture without a golden fails here until the golden exists;
regenerate deliberately with ``python tests/emit_fixtures.py tests/golden``
and review the diff.

Byte comparison is the contract: anything below — key order, quoting,
indentation, the trailing newline — is part of the promised output. The one
normalized exception is the version inside the generated-by comment: a
version bump must not invalidate every golden, so both sides have it folded
to a fixed token here, and the line's exact format is asserted by a
dedicated unit test in test_emit.py instead.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from emit_fixtures import FIXTURES, emit_fixture

GOLDEN = Path(__file__).resolve().parent / "golden"

FIXTURE_NAMES = sorted(p.name for p in FIXTURES.iterdir() if p.is_dir())

_GENERATED_BY_VERSION = re.compile(rb"^(# Generated by autocore )v\S+", re.M)


def _normalized(data: bytes) -> bytes:
    """`data` with the generated-by version folded to a fixed token."""
    return _GENERATED_BY_VERSION.sub(rb"\1vVERSION", data)


def test_every_fixture_is_discovered() -> None:
    # Guards the discovery itself: an empty parametrize list would pass
    # silently if the fixtures directory moved.
    assert FIXTURE_NAMES


@pytest.mark.parametrize("name", FIXTURE_NAMES)
def test_fixture_output_matches_its_golden_up_to_the_version(name: str) -> None:
    golden = GOLDEN / f"{name}.core"
    assert golden.is_file(), (
        f"no golden for fixture '{name}' — generate it with "
        "'python tests/emit_fixtures.py tests/golden' and review it"
    )

    text = emit_fixture(FIXTURES / name)

    assert _normalized(text.encode("utf-8")) == _normalized(golden.read_bytes())
